name: Build TFE

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
          # - windows-latest
          # - macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: sudo apt-get update -qq && sudo apt-get install -y libsdl2-dev libsdl2-image-dev

    - name: Configure cmake
      shell: bash
      run: |
        cmake -B ./build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DENABLE_FORCE_SCRIPT=ON \
          -DENABLE_EDITOR=ON

    - name: Build
      shell: bash
      run: cmake --build ./build --config ${{env.BUILD_TYPE}}
